/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Cbyqi18jq1G
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Archivo } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem } from "@/components/ui/carousel"

export function Demo() {
  return (
    (<Carousel
      className="w-screen h-screen"
      opts={{ loop: true, autoplay: true, interval: 5000, pauseOnHover: false }}>
      <CarouselContent>
        <CarouselItem>
          <img
            src="/placeholder.svg"
            alt="Hero Image"
            className="w-full h-full object-cover" />
        </CarouselItem>
        <CarouselItem>
          <img
            src="/placeholder.svg"
            alt="Hero Image"
            className="w-full h-full object-cover" />
        </CarouselItem>
        <CarouselItem>
          <img
            src="/placeholder.svg"
            alt="Hero Image"
            className="w-full h-full object-cover" />
        </CarouselItem>
      </CarouselContent>
    </Carousel>)
  );
}
